name: Test Token Exchange

on:
  pull_request:

jobs:
  test:
    name: Test Token Exchange
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get P6M YBOR Token
        uses: ./
        with:
          platform_token_exchange_url: https://auth-dev.p6m.dev/api/github/actions/token-exchange
