name: Test Token Exchange

on:
  pull_request:
  workflow_dispatch:
    inputs:
      hostname:
        description: Token exchange hostname
        required: false
        default: auth.p6m.dev

jobs:
  test:
    name: Test Token Exchange
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get P6M YBOR Token
        uses: ./
        with:
          platform_token_exchange_url: https://${{ inputs.hostname || 'macbook-ybor.rockhopper-hen.ts.net' }}/api/github/actions/token-exchange
